"""
Deployment Agent
Packages the tuned model as a live FastAPI REST endpoint.
Generates app.py, Dockerfile, and requirements.txt in sessions/{id}/api/.
Starts the API locally and validates it with a health check + test prediction.
"""

import json
import pickle
import shutil
from pathlib import Path

import pandas as pd


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def _generate_api_code(model_path: str, scaler_path, feature_columns: list,
                        target_col: str, task_type: str) -> str:
    has_scaler    = scaler_path is not None
    is_classifier = "classification" in task_type

    scaler_load = ""
    if has_scaler:
        scaler_load = f"""
try:
    with open(SCALER_PATH, "rb") as f:
        scaler = pickle.load(f)
    logger.info("Scaler loaded successfully")
except Exception as e:
    logger.error(f"Failed to load scaler: {{e}}")
    raise
"""
    else:
        scaler_load = "\nscaler = None\n"

    prob_field   = 'probability: Optional[float] = None' if is_classifier else ''
    pred_cast    = 'int(prediction)' if is_classifier else 'float(prediction)'
    prob_compute = (
        "prob = float(model.predict_proba(X)[0].max()) "
        "if hasattr(model, 'predict_proba') else None"
        if is_classifier else "prob = None"
    )
    prob_assign  = "probability=prob," if is_classifier else ""

    scaler_path_line = (
        f'SCALER_PATH = Path("{scaler_path}")'
        if has_scaler else "SCALER_PATH = None"
    )

    return f'''"""
Auto-generated Prediction API
Model: {model_path}
Generated by the Data Science Pipeline
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, validator
from typing import Optional, Dict, Any
import pandas as pd
import pickle
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Prediction API",
    description="Accepts data and returns model predictions.",
    version="1.0.0"
)

MODEL_PATH      = Path("{model_path}")
{scaler_path_line}

FEATURE_COLUMNS = {feature_columns}
TARGET_COL      = "{target_col}"

try:
    with open(MODEL_PATH, "rb") as f:
        model = pickle.load(f)
    logger.info("Model loaded successfully")
except Exception as e:
    logger.error(f"Failed to load model: {{e}}")
    raise
{scaler_load}

class PredictionRequest(BaseModel):
    """Input data for a single prediction."""
    data: Dict[str, Any]

    @validator("data")
    def validate_features(cls, v):
        missing = [c for c in FEATURE_COLUMNS if c not in v]
        if missing:
            raise ValueError(
                f"Missing required fields: {{missing}}. "
                f"Required fields are: {{FEATURE_COLUMNS}}"
            )
        return v


class PredictionResponse(BaseModel):
    """Prediction result."""
    prediction: Any
    {prob_field}
    message: str


@app.get("/health")
def health_check():
    """Check that the API is running and the model is loaded."""
    return {{
        "status":  "healthy",
        "model":   str(MODEL_PATH.name),
        "message": "The prediction API is running and ready to accept requests."
    }}


@app.post("/predict", response_model=PredictionResponse)
def predict(request: PredictionRequest):
    """
    Make a prediction for a single row of data.

    Send a JSON object with a 'data' field containing your feature values.
    Example:
    {{
        "data": {{
            "feature_1": value,
            "feature_2": value
        }}
    }}
    """
    try:
        X = pd.DataFrame([request.data])[FEATURE_COLUMNS]

        if scaler is not None:
            numeric_cols = X.select_dtypes("number").columns.tolist()
            X[numeric_cols] = scaler.transform(X[numeric_cols])

        prediction = model.predict(X)[0]
        {prob_compute}

        return PredictionResponse(
            prediction={pred_cast},
            {prob_assign}
            message="Prediction complete."
        )

    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        logger.error(f"Prediction error: {{e}}")
        raise HTTPException(status_code=500,
                            detail="An error occurred during prediction.")


@app.get("/features")
def list_features():
    """List the fields required to make a prediction."""
    return {{
        "required_fields": FEATURE_COLUMNS,
        "target":          TARGET_COL,
        "message": (
            f"Send these {{len(FEATURE_COLUMNS)}} fields in the 'data' object "
            f"to the /predict endpoint."
        )
    }}
'''


def _generate_dockerfile() -> str:
    return """FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY models/ ./models/

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
"""


def _generate_requirements() -> str:
    return """fastapi>=0.104.0
uvicorn>=0.24.0
pydantic>=2.0.0
pandas>=2.0.0
scikit-learn>=1.3.0
xgboost>=2.0.0
"""


# ---------------------------------------------------------------------------
# File I/O and API lifecycle
# ---------------------------------------------------------------------------

def _write_api_files(session_id: str, api_code: str,
                     dockerfile: str, requirements: str) -> Path:
    api_dir = Path("sessions") / session_id / "api"
    api_dir.mkdir(parents=True, exist_ok=True)

    (api_dir / "app.py").write_text(api_code, encoding="utf-8")
    (api_dir / "Dockerfile").write_text(dockerfile, encoding="utf-8")
    (api_dir / "requirements.txt").write_text(requirements, encoding="utf-8")

    # Copy model files into api/ for Docker portability
    models_src = Path("sessions") / session_id / "models"
    models_dst = api_dir / "models"
    if models_src.exists():
        shutil.copytree(str(models_src), str(models_dst), dirs_exist_ok=True)

    return api_dir


def _test_model_in_process(model_path: Path, splits_dir: Path,
                            feature_columns: list) -> tuple[bool, dict]:
    """Load the model and run one prediction in-process to verify it works."""
    try:
        with open(model_path, "rb") as f:
            model = pickle.load(f)
        X_sample = pd.read_csv(splits_dir / "X_val.csv", nrows=1)[feature_columns]
        prediction = model.predict(X_sample)[0]
        result = {"prediction": str(prediction)}
        if hasattr(model, "predict_proba"):
            try:
                proba = float(model.predict_proba(X_sample)[0].max())
                result["confidence"] = round(proba, 4)
            except Exception:
                pass
        return True, result
    except Exception as exc:
        return False, {"error": str(exc)}


# ---------------------------------------------------------------------------
# run()
# ---------------------------------------------------------------------------

def run(session: dict, decisions: dict) -> dict:
    session_id   = session["session_id"]
    target_col   = session["goal"].get("target_column")
    task_type    = session["goal"].get("task_type", "binary_classification")
    sessions_dir = Path("sessions")
    session_dir  = sessions_dir / session_id
    splits_dir   = session_dir / "data" / "processed" / "splits"

    # Load model — prefer tuned
    tuned_path = session_dir / "models" / "tuned_model.pkl"
    best_json  = session_dir / "models" / "best_model.json"

    if tuned_path.exists():
        model_path = tuned_path
    elif best_json.exists():
        with open(best_json) as f:
            model_info = json.load(f)
        model_path = Path(model_info["model_path"])
    else:
        return {
            "stage":                 "deployment",
            "status":                "failed",
            "plain_english_summary": "No trained model found. Please run training first."
        }

    scaler_path_obj = session_dir / "models" / "scaler.pkl"
    scaler_path     = str(scaler_path_obj) if scaler_path_obj.exists() else None

    # Load feature columns from training splits
    try:
        X_train = pd.read_csv(splits_dir / "X_train.csv", nrows=5)
        feature_columns = X_train.columns.tolist()
    except FileNotFoundError:
        return {
            "stage":                 "deployment",
            "status":                "failed",
            "plain_english_summary": "No split data found. Please run splitting first."
        }

    # Load a sample row for test prediction
    try:
        X_val  = pd.read_csv(splits_dir / "X_val.csv")
        sample_row = X_val.iloc[0].tolist()
    except Exception:
        sample_row = [0] * len(feature_columns)

    # Generate API files
    api_code     = _generate_api_code(
        str(model_path), scaler_path, feature_columns, target_col, task_type
    )
    dockerfile   = _generate_dockerfile()
    requirements = _generate_requirements()

    api_dir = _write_api_files(session_id, api_code, dockerfile, requirements)

    # In-process test — verify the model loads and predicts without launching a server
    test_passed, test_response = _test_model_in_process(
        model_path, splits_dir, feature_columns
    )

    run_cmd = f"cd sessions/{session_id}/api && uvicorn app:app --port 8000"
    summary = (
        f"Your model and API code have been packaged and saved to: sessions/{session_id}/api/. "
        f"To start the live API, run: {run_cmd} "
        f"Once running, send data to http://localhost:8000/predict to get predictions, "
        f"or open http://localhost:8000/docs to use the interactive interface."
    )

    return {
        "stage":                 "deployment",
        "status":                "success",
        "api_dir":               str(api_dir),
        "run_command":           run_cmd,
        "test_passed":           test_passed,
        "test_prediction_result": test_response,
        "feature_columns":       feature_columns,
        "decisions_required":    [],
        "decisions_made":        [],
        "plain_english_summary": summary,
        "report_section": {
            "stage":   "deployment",
            "title":   "Packaging Your Model for Deployment",
            "summary": summary,
            "decision_made": "Generated API code, Dockerfile, and requirements.txt.",
            "why_this_matters": (
                "Deployment packages the model into a ready-to-run web service. "
                "Any application that can make a web request can use your model "
                "to make predictions on new data."
            )
        },
        "config_updates": {
            "api_dir": str(api_dir)
        }
    }
